import { Room } from '@/types/room'

export const rooms: Room[] = [
  {
    id: '1',
    slug: 'deluxe-room',
    name: 'Deluxe Room',
    description: 'Our Deluxe Rooms offer an elegant retreat with sweeping city views, premium Egyptian cotton bedding, and a marble en-suite bathroom. Every detail has been carefully considered to ensure your utmost comfort.',
    pricePerNight: 8500,
    capacity: 2,
    bedType: 'queen',
    amenities: ['Free WiFi', 'Air Conditioning', 'Mini Bar', 'Room Service', 'Flat Screen TV', 'Safe', 'Bathrobes', 'Coffee Maker'],
    images: [],
    status: 'available',
    rating: 4.8,
    reviewCount: 124,
    size: 35,
    floor: 5,
    featured: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '2',
    slug: 'superior-room',
    name: 'Superior Room',
    description: 'The Superior Room combines modern luxury with warm Filipino hospitality. Featuring a plush king bed, workspace, and a rain shower bathroom with premium amenities.',
    pricePerNight: 11000,
    capacity: 2,
    bedType: 'king',
    amenities: ['Free WiFi', 'Air Conditioning', 'Mini Bar', 'Room Service', 'Flat Screen TV', 'Safe', 'Bathrobes', 'Rain Shower', 'Workspace'],
    images: [],
    status: 'available',
    rating: 4.9,
    reviewCount: 89,
    size: 45,
    floor: 8,
    featured: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '3',
    slug: 'junior-suite',
    name: 'Junior Suite',
    description: 'The Junior Suite offers a generous separate living area, panoramic city views, and an indulgent soaking tub. Perfect for those who desire extra space and refined comfort.',
    pricePerNight: 15000,
    capacity: 3,
    bedType: 'king',
    amenities: ['Free WiFi', 'Air Conditioning', 'Mini Bar', 'Room Service', 'Flat Screen TV', 'Safe', 'Bathrobes', 'Soaking Tub', 'Living Area', 'Butler Service'],
    images: [],
    status: 'available',
    rating: 4.9,
    reviewCount: 67,
    size: 65,
    floor: 12,
    featured: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '4',
    slug: 'executive-suite',
    name: 'Executive Suite',
    description: 'Designed for the discerning traveler, the Executive Suite features a grand bedroom, spacious living room, private dining area, and access to our exclusive Executive Lounge.',
    pricePerNight: 22000,
    capacity: 3,
    bedType: 'king',
    amenities: ['Free WiFi', 'Air Conditioning', 'Mini Bar', 'Room Service', 'Flat Screen TV', 'Safe', 'Bathrobes', 'Soaking Tub', 'Living Area', 'Butler Service', 'Executive Lounge', 'Private Dining'],
    images: [],
    status: 'available',
    rating: 5.0,
    reviewCount: 43,
    size: 85,
    floor: 15,
    featured: false,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '5',
    slug: 'penthouse-suite',
    name: 'Penthouse Suite',
    description: 'The crown jewel of Hotel Lumière. Our Penthouse Suite spans the entire top floor with a private terrace, plunge pool, grand piano, and 360-degree panoramic views of Manila.',
    pricePerNight: 28000,
    capacity: 4,
    bedType: 'king',
    amenities: ['Free WiFi', 'Air Conditioning', 'Full Bar', 'Room Service', 'Multiple TVs', 'Safe', 'Bathrobes', 'Plunge Pool', 'Private Terrace', 'Grand Piano', 'Butler Service', 'Private Chef'],
    images: [],
    status: 'available',
    rating: 5.0,
    reviewCount: 28,
    size: 200,
    floor: 20,
    featured: false,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '6',
    slug: 'presidential-suite',
    name: 'Presidential Suite',
    description: 'The pinnacle of luxury at Hotel Lumière. The Presidential Suite offers unrivaled opulence with a private grand terrace, dedicated concierge, and bespoke experiences crafted just for you.',
    pricePerNight: 35000,
    capacity: 4,
    bedType: 'king',
    amenities: ['Free WiFi', 'Air Conditioning', 'Full Bar', 'Room Service', 'Multiple TVs', 'Safe', 'Bathrobes', 'Plunge Pool', 'Private Terrace', 'Grand Piano', 'Dedicated Concierge', 'Private Chef', 'Airport Transfer'],
    images: [],
    status: 'available',
    rating: 5.0,
    reviewCount: 19,
    size: 320,
    floor: 20,
    featured: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
]

export const getRoomBySlug = (slug: string) => rooms.find(r => r.slug === slug)
